<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class MemberRepository {
		private $_pdo;
		private $_lang;
		private $_pdoHelper;

		public function __construct($pdo, $lang){
			$this->_pdoHelper = $pdo;
			$this->_pdo = $pdo->GetConnection();
			$this->_lang = $lang;
		}

		/**************************
		 * REPOSITORIES FUNCTIONS *
		 **************************/
		public function getAll(){
			$query = "SELECT * FROM member";
			try {
				return $this->_pdo->SelectTable($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function getById($id){
			$query = "SELECT * FROM member WHERE id=" . $id;
			try {
				$properties = $this->_pdo->Select($query);
				$object = new Member();
				$object->fillObject($properties);
				return $object;
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function delete($id) {
			$query = "DELETE FROM member WHERE id=" . $id;
			try {
				return $this->_pdo->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function add($properties) {
			$query = "INSERT INTO member('id', 'name', 'firstname', 'surname', 'picture', 'birthday', 'instrument', 'influences', 'description', 'lang')
				VALUES(" . $properties["id"] . ", '" . $properties["name"] . "', '" . $properties["firstname"] . "', '" . $properties["surname"] . "', '" . $properties["picture"] . "', '" . $properties["birthday"] . "', '" . $properties["instrument"] . "', '" . $properties["influences"] . "', '" . $properties["description"] . "', '" . $properties["lang"] . "')";
			try {
				return $this->_pdo->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function update($id, $properties) {
			$query = "UPDATE member 
				SET id = " . $properties["id"] . ", name = '" . $properties["name"] . "', firstname = '" . $properties["firstname"] . "', surname = '" . $properties["surname"] . "', picture = '" . $properties["picture"] . "', birthday = '" . $properties["birthday"] . "', instrument = '" . $properties["instrument"] . "', influences = '" . $properties["influences"] . "', description = '" . $properties["description"] . "', lang = '" . $properties["lang"] . "'
				WHERE id=" . $id;
			try {
				return $this->_pdo->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}
		/*******
		 * END *
		 *******/

	}
?>