<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class UserRepository {
		private $_pdo;
		private $_lang;
		private $_pdoHelper;

		public function __construct($pdo, $lang){
			$this->_pdoHelper = $pdo;
			$this->_pdo = $pdo->GetConnection();
			$this->_lang = $lang;
		}
		
		public function getByLogin($login, $pwd){
			$query = "SELECT * FROM user WHERE login='" . $login . "' AND password='" . md5($pwd) . "'";
			try {
				return $this->_pdoHelper->SelectTable($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		/**************************
		 * REPOSITORIES FUNCTIONS *
		 **************************/
		public function getAll(){
			$query = "SELECT * FROM user";
			try {
				return $this->_pdoHelper->SelectTable($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function getById($id){
			$query = "SELECT * FROM user WHERE id=" . $id;
			try {
				$properties = $this->_pdoHelper->Select($query);
				$object = new User();
				$object->fillObject($properties);
				return $object;
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function delete($id) {
			$query = "DELETE FROM user WHERE id=" . $id;
			try {
				return $this->_pdoHelper->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function add($properties) {
			$query = "INSERT INTO user('id', 'login', 'password', 'email', 'role')
				VALUES(" . $properties["id"] . ", '" . $properties["login"] . "', '" . $properties["password"] . "', '" . $properties["email"] . "', " . $properties["role"] . ")";
			try {
				return $this->_pdoHelper->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function update($id, $properties) {
			$query = "UPDATE user 
				SET id = " . $properties["id"] . ", login = '" . $properties["login"] . "', password = '" . $properties["password"] . "', email = '" . $properties["email"] . "', role = " . $properties["role"] . "
				WHERE id=" . $id;
			try {
				return $this->_pdoHelper->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}
		/*******
		 * END *
		 *******/

	}
?>