<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class Header {
		private $_id;
		private $_title;
		private $_metaDescription;
		private $_metaKeywords;
		private $_lang;

		public function __construct($id, $title, $metaDescription, $metaKeywords, $lang){
			$this->fillObject(array("id" => $id, "title" => $title, "metaDescription" => $metaDescription, "metaKeywords" => $metaKeywords, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getMetaDescription() {
			return $this->_metaDescription;
		}
		public function getMetaKeywords() {
			return $this->_metaKeywords;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			$this->_id = $properties["id"];
			$this->_title = $properties["title"];
			$this->_metaDescription = $properties["metaDescription"];
			$this->_metaKeywords = $properties["metaKeywords"];
			$this->_lang = $properties["lang"];
		}
	}
?>