<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class Song {
		private $_id;
		private $_filename;
		private $_title;
		private $_description;
		private $_duration;
		private $_lang;

		public function __construct($id, $filename, $title, $description, $duration, $lang){
			$this->fillObject(array("id" => $id, "filename" => $filename, "title" => $title, "description" => $description, "duration" => $duration, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getFilename() {
			return $this->_filename;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getDuration() {
			return $this->_duration;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			$this->_id = $properties["id"];
			$this->_filename = $properties["filename"];
			$this->_title = $properties["title"];
			$this->_description = $properties["description"];
			$this->_duration = $properties["duration"];
			$this->_lang = $properties["lang"];
		}
	}
?>