<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core as cores;

	class Album {
		private $_id;
		private $_title;
		private $_description;
		private $_date;
		private $_thumb;
		private $_lang;
		private $_songs;
		private $_queryBuilder;

		public function __construct($id = "", $title = "", $description = "", $date = "", $thumb = "", $lang = ""){
			$this->_queryBuilder = new cores\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "title" => $title, "description" => $description, "date" => $date, "thumb" => $thumb, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getDate() {
			return $this->_date;
		}
		public function getThumb() {
			return $this->_thumb;
		}
		public function getLang() {
			return $this->_lang;
		}
		public function getSongs() {
			$query = $this->_queryBuilder->select() 
											  ->from("song")
											  ->where(array(array("link" => "", "left" => "idAlbum", "operator" => "=", "right" => $this->_id)))->getQuery();
			try {
				$result = $this->_pdo->SelectTable($query);
				$array = array();
				foreach ($result as $object){
					$o = new Song();
					$o->fillObject($object);
					$array[] = $o;
				}
				return $array;
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["date"]))
				$this->_date = $properties["date"];
			if(!empty($properties["thumb"]))
				$this->_thumb = $properties["thumb"];
			if(!empty($properties["lang"]))
				$this->_lang = $properties["lang"];
		}
	}
