<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core as cores;

	class Event {
		private $_id;
		private $_title;
		private $_description;
		private $_date;
		private $_type;
		private $_lang;
		private $_queryBuilder;

		public function __construct($id = "", $title = "", $description = "", $date = "", $type = "", $lang = ""){
			$this->_queryBuilder = new cores\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "title" => $title, "description" => $description, "date" => $date, "type" => $type, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getDate() {
			return $this->_date;
		}
		public function getType() {
			return $this->_type;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["date"]))
				$this->_date = $properties["date"];
			if(!empty($properties["type"]))
				$this->_type = $properties["type"];
			if(!empty($properties["lang"]))
				$this->_lang = $properties["lang"];
		}
	}
