<?php

    /* *********************************************************
     * *** File generated by fitzlucassen\DALGenerator tool ****
     * All right reserved to fitzlucassen repository on github *
     * ************ https://github.com/fitzlucassen ************
     * *********************************************************/

    class Header {

	private $_id;
	private $_title;
	private $_metaDescription;
	private $_metaKeywords;
	private $_lang;

	public function __construct($id, $title, $metaDescription, $metaKeywords, $lang) {
	    $this->fillObject(array("id" => $id, "title" => $title, "metaDescription" => $metaDescription, "metaKeywords" => $metaKeywords, "lang" => $lang));
	}

	/***********
	 * GETTERS *
	 ***********/
	/**
	 * 
	 * @return type
	 */
	public function getId() {
	    return $this->_id;
	}
	/**
	 * 
	 * @return type
	 */
	public function getTitle() {
	    return $this->_title;
	}
	/**
	 * 
	 * @return type
	 */
	public function getMetaDescription() {
	    return $this->_metaDescription;
	}
	/**
	 * 
	 * @return type
	 */
	public function getMetaKeywords() {
	    return $this->_metaKeywords;
	}
	/**
	 * 
	 * @return type
	 */
	public function getLang() {
	    return $this->_lang;
	}
	/*******
	 * END *
	 *******/

	/**
	 * 
	 * @param type $properties
	 */
	public function fillObject($properties) {
	    $this->_id = $properties["id"];
	    $this->_title = $properties["title"];
	    $this->_metaDescription = $properties["metaDescription"];
	    $this->_metaKeywords = $properties["metaKeywords"];
	    $this->_lang = $properties["lang"];
	}
    }