<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core as cores;

	class Member {
		private $_id;
		private $_name;
		private $_firstname;
		private $_surname;
		private $_picture;
		private $_birthday;
		private $_instrument;
		private $_influences;
		private $_description;
		private $_lang;
		private $_queryBuilder;

		public function __construct($id = "", $name = "", $firstname = "", $surname = "", $picture = "", $birthday = "", $instrument = "", $influences = "", $description = "", $lang = ""){
			$this->_queryBuilder = new cores\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "name" => $name, "firstname" => $firstname, "surname" => $surname, "picture" => $picture, "birthday" => $birthday, "instrument" => $instrument, "influences" => $influences, "description" => $description, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getName() {
			return $this->_name;
		}
		public function getFirstname() {
			return $this->_firstname;
		}
		public function getSurname() {
			return $this->_surname;
		}
		public function getPicture() {
			return $this->_picture;
		}
		public function getBirthday() {
			return $this->_birthday;
		}
		public function getInstrument() {
			return $this->_instrument;
		}
		public function getInfluences() {
			return $this->_influences;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["name"]))
				$this->_name = $properties["name"];
			if(!empty($properties["firstname"]))
				$this->_firstname = $properties["firstname"];
			if(!empty($properties["surname"]))
				$this->_surname = $properties["surname"];
			if(!empty($properties["picture"]))
				$this->_picture = $properties["picture"];
			if(!empty($properties["birthday"]))
				$this->_birthday = $properties["birthday"];
			if(!empty($properties["instrument"]))
				$this->_instrument = $properties["instrument"];
			if(!empty($properties["influences"]))
				$this->_influences = $properties["influences"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["lang"]))
				$this->_lang = $properties["lang"];
		}
	}
