<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class Member {
		private $_id;
		private $_name;
		private $_firstname;
		private $_surname;
		private $_picture;
		private $_birthday;
		private $_instrument;
		private $_influences;
		private $_description;
		private $_lang;

		public function __construct($id, $name, $firstname, $surname, $picture, $birthday, $instrument, $influences, $description, $lang){
			$this->fillObject(array("id" => $id, "name" => $name, "firstname" => $firstname, "surname" => $surname, "picture" => $picture, "birthday" => $birthday, "instrument" => $instrument, "influences" => $influences, "description" => $description, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getName() {
			return $this->_name;
		}
		public function getFirstname() {
			return $this->_firstname;
		}
		public function getSurname() {
			return $this->_surname;
		}
		public function getPicture() {
			return $this->_picture;
		}
		public function getBirthday() {
			return $this->_birthday;
		}
		public function getInstrument() {
			return $this->_instrument;
		}
		public function getInfluences() {
			return $this->_influences;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			$this->_id = $properties["id"];
			$this->_name = $properties["name"];
			$this->_firstname = $properties["firstname"];
			$this->_surname = $properties["surname"];
			$this->_picture = $properties["picture"];
			$this->_birthday = $properties["birthday"];
			$this->_instrument = $properties["instrument"];
			$this->_influences = $properties["influences"];
			$this->_description = $properties["description"];
			$this->_lang = $properties["lang"];
		}
	}
?>