<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class Rewrittingurl {
		private $_id;
		private $_routeurl;
		private $_idRouteUrl;
		private $_urlMatched;
		private $_lang;

		public function __construct($id, $idRouteUrl, $urlMatched, $lang){
			$this->fillObject(array("id" => $id, "idRouteUrl" => $idRouteUrl, "urlMatched" => $urlMatched, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getRouteUrl() {
			$query = "SELECT * FROM routeurl WHERE idRouteurl=" . $this->_idRouteurl;
			try {
				return $this->_pdo->Select($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function getIdRouteUrl() {
			return $this->_idRouteUrl;
		}
		public function getUrlMatched() {
			return $this->_urlMatched;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			$this->_id = $properties["id"];
			$this->_idRouteUrl = $properties["idRouteUrl"];
			$this->_urlMatched = $properties["urlMatched"];
			$this->_lang = $properties["lang"];
		}
	}
?>