<?php

    /* *********************************************************
     * *** File generated by fitzlucassen\DALGenerator tool ****
     * All right reserved to fitzlucassen repository on github *
     * ************ https://github.com/fitzlucassen ************
     * *********************************************************/

    class Rewrittingurl {

	private $_id;
	private $_idRoute;
	private $_urlMatched;
	private $_lang;

	public function __construct($id, $idRoute, $urlMatched, $lang) {
	    $this->fillObject(array("id" => $id, "idRoute" => $idRoute, "urlMatched" => $urlMatched, "lang" => $lang));
	}

	/***********
	 * GETTERS *
	 ***********/
	/**
	 * 
	 * @return type
	 */
	public function getId() {
	    return $this->_id;
	}
	/**
	 * 
	 * @return type
	 */
	public function getIdRoute() {
	    return $this->_idRoute;
	}
	/**
	 * 
	 * @return type
	 */
	public function getUrlMatched() {
	    return $this->_urlMatched;
	}
	/**
	 * 
	 * @return type
	 */
	public function getLang() {
	    return $this->_lang;
	}
	/*******
	 * END *
	 *******/

	/**
	 * 
	 * @param type $properties
	 */
	public function fillObject($properties) {
	    $this->_id = $properties["id"];
	    $this->_idRoute = $properties["idRoute"];
	    $this->_urlMatched = $properties["urlMatched"];
	    $this->_lang = $properties["lang"];
	}
    }