<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class Routeurl {
		private $_id;
		private $_name;
		private $_controller;
		private $_action;
		private $_order;
		private $_rewrittingurls;

		public function __construct($id, $name, $controller, $action, $order){
			$this->fillObject(array("id" => $id, "name" => $name, "controller" => $controller, "action" => $action, "order" => $order));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getName() {
			return $this->_name;
		}
		public function getController() {
			return $this->_controller;
		}
		public function getAction() {
			return $this->_action;
		}
		public function getOrder() {
			return $this->_order;
		}
		public function getRewrittingurls() {
			$query = "SELECT * FROM rewrittingurl WHERE idRouteurl=" . $this->_id;
			try {
				return $this->_pdo->SelectTable($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			$this->_id = $properties["id"];
			$this->_name = $properties["name"];
			$this->_controller = $properties["controller"];
			$this->_action = $properties["action"];
			$this->_order = $properties["order"];
		}
	}
?>