<?php 
    /**********************************************************
     **** File generated by fitzlucassen\DALGenerator tool ****
     * All right reserved to fitzlucassen repository on github*
     ************* https://github.com/fitzlucassen ************
     **********************************************************/
    class Routeurl {
	private $_id;
	private $_name;
	private $_controller;
	private $_action;
	private $_order;

	public function __construct($id, $name, $controller, $action, $order){
	    $this->fillObject(array("id" => $id, "name" => $name, "controller" => $controller, "action" => $action, "order" => $order));
	}

	/***********
	 * GETTERS *
	 ***********/
	/**
	 * 
	 * @return type
	 */
	public function getId() {
	    return $this->_id;
	}
	/**
	 * 
	 * @return type
	 */
	public function getName() {
	    return $this->_name;
	}
	/**
	 * 
	 * @return type
	 */
	public function getController() {
	    return $this->_controller;
	}
	/**
	 * 
	 * @return type
	 */
	public function getAction() {
	    return $this->_action;
	}
	/**
	 * 
	 * @return type
	 */
	public function getOrder() {
	    return $this->_order;
	}
	/*******
	 * END *
	 *******/

	/**
	 * 
	 * @param type $properties
	 */
	public function fillObject($properties) {
	    $this->_id = $properties["id"];
	    $this->_name = $properties["name"];
	    $this->_controller = $properties["controller"];
	    $this->_action = $properties["action"];
	    $this->_order = $properties["order"];
	}
    }