<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class Song {
		private $_id;
		private $_filename;
		private $_title;
		private $_description;
		private $_duration;
		private $_lang;
		private $_album;
		private $_idAlbum;

		public function __construct($id, $filename, $title, $description, $duration, $lang, $idAlbum){
			$this->fillObject(array("id" => $id, "filename" => $filename, "title" => $title, "description" => $description, "duration" => $duration, "lang" => $lang, "idAlbum" => $idAlbum));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getFilename() {
			return $this->_filename;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getDuration() {
			return $this->_duration;
		}
		public function getLang() {
			return $this->_lang;
		}
		public function getAlbum() {
			$query = "SELECT * FROM album WHERE idAlbum=" . $this->_idAlbum;
			try {
				return $this->_pdo->Select($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function getIdAlbum() {
			return $this->_idAlbum;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			$this->_id = $properties["id"];
			$this->_filename = $properties["filename"];
			$this->_title = $properties["title"];
			$this->_description = $properties["description"];
			$this->_duration = $properties["duration"];
			$this->_lang = $properties["lang"];
			$this->_idAlbum = $properties["idAlbum"];
		}
	}
?>