<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class User {
		private $_id;
		private $_login;
		private $_password;
		private $_email;
		private $_role;

		public function __construct($id, $login, $password, $email, $role){
			$this->fillObject(array("id" => $id, "login" => $login, "password" => $password, "email" => $email, "role" => $role));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getLogin() {
			return $this->_login;
		}
		public function getPassword() {
			return $this->_password;
		}
		public function getEmail() {
			return $this->_email;
		}
		public function getRole() {
			return $this->_role;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			$this->_id = $properties["id"];
			$this->_login = $properties["login"];
			$this->_password = $properties["password"];
			$this->_email = $properties["email"];
			$this->_role = $properties["role"];
		}
	}
?>