<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core as cores;

	class Video {
		private $_id;
		private $_url;
		private $_title;
		private $_description;
		private $_thumb;
		private $_lang;
		private $_queryBuilder;

		public function __construct($id = "", $url = "", $title = "", $description = "", $thumb = "", $lang = ""){
			$this->_queryBuilder = new cores\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "url" => $url, "title" => $title, "description" => $description, "thumb" => $thumb, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getUrl() {
			return $this->_url;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getThumb() {
			return $this->_thumb;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["url"]))
				$this->_url = $properties["url"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["thumb"]))
				$this->_thumb = $properties["thumb"];
			if(!empty($properties["lang"]))
				$this->_lang = $properties["lang"];
		}
	}
