<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class SongRepository {
		private $_pdo;
		private $_lang;
		private $_pdoHelper;

		public function __construct($pdo, $lang){
			$this->_pdoHelper = $pdo;
			$this->_pdo = $pdo->GetConnection();
			$this->_lang = $lang;
		}

		/**************************
		 * REPOSITORIES FUNCTIONS *
		 **************************/
		public function getAll(){
			$query = "SELECT * FROM song";
			try {
				return $this->_pdo->SelectTable($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function getById($id){
			$query = "SELECT * FROM song WHERE id=" . $id;
			try {
				$properties = $this->_pdo->Select($query);
				$object = new Song();
				$object->fillObject($properties);
				return $object;
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function delete($id) {
			$query = "DELETE FROM song WHERE id=" . $id;
			try {
				return $this->_pdo->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function add($properties) {
			$query = "INSERT INTO song('id', 'filename', 'title', 'description', 'duration', 'lang')
				VALUES(" . $properties["id"] . ", '" . $properties["filename"] . "', '" . $properties["title"] . "', '" . $properties["description"] . "', '" . $properties["duration"] . "', '" . $properties["lang"] . "')";
			try {
				return $this->_pdo->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function update($id, $properties) {
			$query = "UPDATE song 
				SET id = " . $properties["id"] . ", filename = '" . $properties["filename"] . "', title = '" . $properties["title"] . "', description = '" . $properties["description"] . "', duration = '" . $properties["duration"] . "', lang = '" . $properties["lang"] . "'
				WHERE id=" . $id;
			try {
				return $this->_pdo->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}
		/*******
		 * END *
		 *******/

	}
?>